baseURL = "http://blog.yunbiu.top"
title = "Shai - BLOG"

languageCode = "zh-cn"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = true

theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
enableGitInfo = true
enableInlineShortcodes = true

[pagination]
disableAliases = false
pagerSize = 8
path = "page"

[minify]
minifyOutput = true

[params]
env = "production"
title = "Shai's Blog"
description = "ä¸€ä¸ªè®°å½•ç”Ÿæ´»å’ŒæŠ€æœ¯çš„åœ°æ–¹"
version = "v2.0.0"  # æ‰‹åŠ¨ç»´æŠ¤ç‰ˆæœ¬å·
buildDate = "2025-01-03"
defaultTheme = "auto"
disableThemeToggle = false
DateFormat = "2006-01-02"
ShowShareButtons = false
fancybox = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = true
comments = true
ShowLastMod = true  # æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´
ShowToc = true # æ˜¾ç¤ºç›®å½•
TocOpen = true # è‡ªåŠ¨å±•å¼€ç›®å½•
UseHugoToc = true

[params.assets]
favicon = "/images/favicon.ico"
disableHLJS = true

[params.homeInfoParams]
title = "Shai's Blog"
content = """
æ€»è¦å†™ç‚¹ä»€ä¹ˆâœğŸ».  
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/ushaio"

[[params.socialIcons]]
name = "telegram"
url = "https://t.me/adandonOA"

[[params.socialIcons]]
name = "email"
url = "mailto:haggi@lao.ac.cn"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[params.editPost]
URL = "https://github.com/ushaio/ushaio.github.io/edit/main/content"
Text = "åœ¨ GitHub ç¼–è¾‘"
appendFilePath = true

[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 0
keys = ["title", "permalink", "summary", "content"]

[markup]
[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
style = "trac"

[[menu.main]]
identifier = "é¦–é¡µ"
name = "é¦–é¡µ"
url = "/"
weight = 1

[[menu.main]]
identifier = "æœç´¢"
name = "æœç´¢"
url = "/search"
weight = 10

[[menu.main]]
identifier = "åˆ†ç±»"
name = "åˆ†ç±»"
url = "/categories"
weight = 20

[[menu.main]]
identifier = "æ ‡ç­¾"
name = "æ ‡ç­¾"
url = "/tags"
weight = 30

[[menu.main]]
identifier = "å½’æ¡£"
name = "å½’æ¡£"
url = "/archives"
weight = 40

[[menu.main]]
identifier = "å‹é“¾"
name = "å‹é“¾"
url = "/links"
weight = 50

[outputs]
home = ["HTML", "RSS", "JSON"]

[privacy]
[privacy.vimeo]
disabled = false
simple = true

# [privacy.twitter]
# disabled = false
# enableDNT = true
# simple = true

# [privacy.instagram]
# disabled = false
# simple = true

# [privacy.youtube]
# disabled = false
# privacyEnhanced = true

[services]
# [services.instagram]
# disableInlineCSS = true
# [services.twitter]
# disableInlineCSS = true